### ISSUE TITLE
Bower problem

### ISSUE THREAD

**Issue by mmanista** [mastahyeti/u2f-api#10]
Hello!
There is a problem with this package when installed by Bower.

Bower.json config file is missing a "main" property, which makes tools like grunt-wiredep not recognizing this as component to inject into the HTML template as a script.

Steps to reproduce:
- bower install u2f-api --save
- grunt bower-install

Adding the following line:
"main": "u2f-api-polyfill.js"
to the bower.json file fixes the problem.

**Comment by btoews** [comment]
Sorry for ignoring this. I hadn't been watching the repo. This is an NPM package, not a bower package, so there isn't any `bower.json` file to add things to.
