### ISSUE TITLE
Type for `u2f.RegisterResponse` is incorrect.

### ISSUE THREAD

**Issue by lgarron** [mastahyeti/u2f-api#12]
The type annotation for `u2f.RegisterResponse` is:

https://github.com/mastahyeti/u2f-api/blob/9127d282ead179c5a4213c22acfb9af897431c8f/u2f-api-polyfill.js#L153-L161

However, in practice, I see:

    // Typescript-style definition
    type RegisterResponse = {
      registrationData: string, // websafe-base64-encoded version of format specified in section 3.3 of https://fidoalliance.org/specs/fido-u2f-v1.0-rd-20140209/fido-u2f-raw-message-formats-v1.0-rd-20140209.pdf
      version: string,
      challenge: string,
      clientData: string // websafe-base64-encoded JSON
    }

Only two of these fields (`registrationData`, `clientData`) are present in the latest reference code, although they might have removed those fields there (since they should match the request values and can be theoretically be omitted):

https://github.com/google/u2f-ref-code/blob/4be9aae6b3c1f422032615eb5d824627b799bbe9/u2f-gae-demo/war/js/u2f-api.js#L113-L120

**Comment by lgarron** [comment]
https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html#h4_dictionary-u2fregisterrequest-members shows:

    dictionary RegisterResponse {
        DOMString version;
        DOMString registrationData;
        DOMString clientData;
    };

**Comment by btoews** [comment]
Sorry for the miscommunication @lgarron. This repo is just a mirror. You should move this issue to https://github.com/google/u2f-ref-code.
