### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sharstream** [mastahyeti/u2f-api#13]
Hello, do you know why I'm getting this error in my u2f-api-polyfill node_modules packages in both 0.4.1 & 0.4.3, any idea? Thx.

<img width="594" alt="screen shot 2018-09-23 at 10 26 35 pm" src="https://user-images.githubusercontent.com/6071127/45936043-f5c6d300-bf7f-11e8-9b3b-14ef25971abd.png">

**Comment by btoews** [comment]
Hi. This package is meant to be used in browsers.

**Comment by sharstream** [comment]
Thanks for the response. It seems a similar issue no resolved like this https://github.com/okta/okta-signin-widget/issues/295
